export const loanTypes = [
  {
    slug: "home-loan",
    name: "Home Loan",
    tagline: "For the house you've been picturing for years.",
    rate: "8.35% – 9.75%",
    tenure: "Up to 30 years",
    maxAmount: "₹5 Crore",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1000&q=80",
    documents: [
      "Identity & address proof (Aadhaar / PAN / Passport)",
      "Last 6 months' bank statements",
      "Last 3 years' income tax returns",
      "Property documents & sale agreement",
      "Salary slips (last 3 months) or business proof for self-employed",
    ],
    eligibility: "Salaried or self-employed, 21–65 years, minimum monthly income of ₹25,000.",
  },
  {
    slug: "car-loan",
    name: "Car Loan",
    tagline: "New or used, drive away sooner.",
    rate: "8.75% – 11.5%",
    tenure: "Up to 7 years",
    maxAmount: "₹1 Crore",
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=1000&q=80",
    documents: [
      "Identity & address proof",
      "Last 3 months' bank statements",
      "Salary slips or ITR for the last 2 years",
      "Vehicle quotation / proforma invoice",
      "Passport-size photographs",
    ],
    eligibility: "Salaried or self-employed, 21–60 years, minimum monthly income of ₹20,000.",
  },
  {
    slug: "education-loan",
    name: "Education Loan",
    tagline: "For the degree that opens the next door.",
    rate: "8.15% – 10.5%",
    tenure: "Up to 15 years",
    maxAmount: "₹1.5 Crore",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1000&q=80",
    documents: [
      "Admission letter from the institution",
      "Fee structure / cost of course",
      "Academic records (10th, 12th, entrance scores)",
      "Co-applicant's (parent/guardian) income proof",
      "Collateral documents, where applicable",
    ],
    eligibility: "Indian national with a confirmed admission; co-applicant required for most cases.",
  },
  {
    slug: "health-loan",
    name: "Health Loan",
    tagline: "Medical care shouldn't wait on savings.",
    rate: "9.5% – 13%",
    tenure: "Up to 5 years",
    maxAmount: "₹25 Lakh",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1000&q=80",
    documents: [
      "Identity & address proof",
      "Hospital estimate or treatment cost letter",
      "Last 3 months' bank statements",
      "Income proof (salary slip / ITR)",
    ],
    eligibility: "21–60 years, valid treatment estimate from a recognised hospital.",
  },
  {
    slug: "personal-loan",
    name: "Personal Loan",
    tagline: "No collateral, no questions about what it's for.",
    rate: "10.5% – 16%",
    tenure: "Up to 5 years",
    maxAmount: "₹40 Lakh",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1000&q=80",
    documents: [
      "Identity & address proof",
      "Last 3 months' bank statements",
      "Latest salary slips or ITR for self-employed",
      "Passport-size photograph",
    ],
    eligibility: "Salaried or self-employed, 21–58 years, minimum monthly income of ₹15,000.",
  },
  {
    slug: "business-loan",
    name: "Business Loan",
    tagline: "Working capital, or room to expand.",
    rate: "11% – 18%",
    tenure: "Up to 10 years",
    maxAmount: "₹2 Crore",
    image: "https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=1000&q=80",
    documents: [
      "Business registration & GST certificate",
      "Last 2 years' financial statements",
      "Last 12 months' bank statements",
      "KYC of proprietor / partners / directors",
    ],
    eligibility: "Business vintage of 2+ years with minimum annual turnover of ₹10 Lakh.",
  },
];

export function getLoanBySlug(slug) {
  return loanTypes.find((l) => l.slug === slug);
}
